export const Pokedex: {[speciesid: string]: SpeciesData} = {
	bloodveldmutatedspecialform: 
	{
		num: -100,
		name = "Bloodveld Mutated Special Form",
		baseStats: {hp: 119, atk: 89, def: 80, spa: 111, spd: 90, spe: 46},
		.types = { TYPE_BUG, TYPE_DARK },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 20,
		.friendship = 0,
		.growthRate = GROWTH_SLOW,
		.eggGroups = { EGG_GROUP_MONSTER, EGG_GROUP_MONSTER },
		.abilities = { ABILITY_HAEMANCY, ABILITY_HUSTLE, ABILITY_LIQUID_OOZE },
		.height = 16.8,
		.weight = 916.3,
	},
	demonlesserosrsform: 
	{
		num: -101,
		name = "Demon Lesser OSRS Form",
		baseStats: {hp: 75, atk: 75, def: 75, spa: 40, spd: 75, spe: 40},
		.types = { TYPE_DARK, TYPE_DARK },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 20,
		.friendship = 70,
		.growthRate = GROWTH_SLOW,
		.eggGroups = { EGG_GROUP_HUMAN_LIKE, EGG_GROUP_HUMAN_LIKE },
		.abilities = { ABILITY_AVERNIC, ABILITY_MOXIE, ABILITY_0 },
		.height = 0,
		.weight = 0,
	},
	jellynormalform: 
	{
		num: -102,
		name = "Jelly Normal Form",
		baseStats: {hp: 100, atk: 50, def: 60, spa: 70, spd: 90, spe: 38},
		.types = { TYPE_POISON, TYPE_GHOST },
		.genderRatio = PERCENT_FEMALE(Genderless),
		.eggCycles = 15,
		.friendship = 70,
		.growthRate = GROWTH_MEDIUM_FAST,
		.eggGroups = { EGG_GROUP_AMORPHOUS, EGG_GROUP_AMORPHOUS },
		.abilities = { ABILITY_GOOEY, ABILITY_CLEAR_BODY, ABILITY_CLEAR_BODY },
		.height = 14.5,
		.weight = 4.5,
	},
	abyssalminionform: 
	{
		num: -103,
		name = "Abyssal Minion Form",
		baseStats: {hp: 53, atk: 61, def: 43, spa: 43, spd: 43, spe: 53},
		.types = { TYPE_BUG, TYPE_BUG },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 15,
		.friendship = 70,
		.growthRate = GROWTH_MEDIUM_SLOW,
		.eggGroups = { EGG_GROUP_BUG, EGG_GROUP_AMORPHOUS },
		.abilities = { ABILITY_ABYSSAL, ABILITY_HYPER_CUTTER, ABILITY_TECHNICIAN },
		.height = 7.9,
		.weight = 276.7,
	},
	giantratcryptform: 
	{
		num: -104,
		name = "Giant Rat Crypt Form",
		baseStats: {hp: 70, atk: 60, def: 60, spa: 60, spd: 70, spe: 50},
		.types = { TYPE_DARK, TYPE_DARK },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 15,
		.friendship = 70,
		.growthRate = GROWTH_MEDIUM_FAST,
		.eggGroups = { EGG_GROUP_FIELD, EGG_GROUP_LIFE },
		.abilities = { ABILITY_POISON_TOUCH, ABILITY_STRONG_JAW, ABILITY_POISON_TOUCH },
		.height = 6.9,
		.weight = 97.5,
	},
	hellhound: 
	{
		num: -105,
		name = "Hellhound",
		baseStats: {hp: 110, atk: 110, def: 55, spa: 75, spd: 55, spe: 110},
		.types = { TYPE_FIRE, TYPE_DARK },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 20,
		.friendship = 70,
		.growthRate = GROWTH_SLOW,
		.eggGroups = { EGG_GROUP_FIELD, EGG_GROUP_LIFE },
		.abilities = { ABILITY_INTIMIDATE, ABILITY_PRESSURE, ABILITY_FLAME_BODY },
		.height = 9.9,
		.weight = 492.1,
	},
	bloodveldinsatiablephysicalform: 
	{
		num: -106,
		name = "Bloodveld Insatiable Physical Form",
		baseStats: {hp: 80, atk: 75, def: 60, spa: 45, spd: 40, spe: 40},
		.types = { TYPE_BUG, TYPE_NORMAL },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 20,
		.friendship = 0,
		.growthRate = GROWTH_SLOW,
		.eggGroups = { EGG_GROUP_MONSTER, EGG_GROUP_MONSTER },
		.abilities = { ABILITY_HAEMANCY, ABILITY_LIQUID_OOZE, ABILITY_LIQUID_OOZE },
		.height = 16.8,
		.weight = 916.3,
	},
	bloodveldinsatiablespecialform: 
	{
		num: -107,
		name = "Bloodveld Insatiable Special Form",
		baseStats: {hp: 80, atk: 65, def: 40, spa: 65, spd: 50, spe: 40},
		.types = { TYPE_BUG, TYPE_DARK },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 20,
		.friendship = 0,
		.growthRate = GROWTH_SLOW,
		.eggGroups = { EGG_GROUP_MONSTER, EGG_GROUP_MONSTER },
		.abilities = { ABILITY_HAEMANCY, ABILITY_HUSTLE, ABILITY_LIQUID_OOZE },
		.height = 16.8,
		.weight = 916.3,
	},
	demongreaterosrsform: 
	{
		num: -108,
		name = "Demon Greater OSRS Form",
		baseStats: {hp: 90, atk: 90, def: 90, spa: 60, spd: 90, spe: 60},
		.types = { TYPE_DARK, TYPE_DARK },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 20,
		.friendship = 70,
		.growthRate = GROWTH_SLOW,
		.eggGroups = { EGG_GROUP_HUMAN_LIKE, EGG_GROUP_HUMAN_LIKE },
		.abilities = { ABILITY_AVERNIC, ABILITY_MOXIE, ABILITY_0 },
		.height = 0,
		.weight = 0,
	},
	abyssaldemonform: 
	{
		num: -109,
		name = "Abyssal Demon Form",
		baseStats: {hp: 67, atk: 111, def: 83, spa: 83, spd: 97, spe: 97},
		.types = { TYPE_PSYCHIC, TYPE_BUG },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 15,
		.friendship = 70,
		.growthRate = GROWTH_MEDIUM_SLOW,
		.eggGroups = { EGG_GROUP_BUG, EGG_GROUP_AMORPHOUS },
		.abilities = { ABILITY_ABYSSAL, ABILITY_HYPER_CUTTER, ABILITY_TECHNICIAN },
		.height = 10.1,
		.weight = 489.9,
	},
	basiliskosrsform: 
	{
		num: -110,
		name = "Basilisk OSRS Form",
		baseStats: {hp: 81, atk: 95, def: 85, spa: 70, spd: 80, spe: 37},
		.types = { TYPE_ROCK, TYPE_DRAGON },
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles = 120,
		.friendship = 0,
		.growthRate = GROWTH_SLOW,
		.eggGroups = { EGG_GROUP_MONSTER, EGG_GROUP_MINERAL },
		.abilities = { ABILITY_PETRIFY, ABILITY_INTIMIDATE, ABILITY_0 },
		.height = 0,
		.weight = 0,
	},
	cockatrice: 
	{
		num: -111,
		name = "Cockatrice",
		baseStats: {hp: 99, atk: 91, def: 79, spa: 45, spd: 94, spe: 60},
		.types = { TYPE_ROCK, TYPE_FLYING },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 20,
		.friendship = 0,
		.growthRate = GROWTH_SLOW,
		.eggGroups = { EGG_GROUP_FLYING, EGG_GROUP_MONSTER },
		.abilities = { ABILITY_PETRIFY, ABILITY_MARVEL_SCALE, ABILITY_ROCK_HEAD },
		.height = 8.9,
		.weight = 127,
	},
	demongreaterblackform: 
	{
		num: -112,
		name = "Demon Greater Black Form",
		baseStats: {hp: 80, atk: 70, def: 60, spa: 90, spd: 80, spe: 100},
		.types = { TYPE_DARK, TYPE_DARK },
		.genderRatio = PERCENT_FEMALE(50),
		.eggCycles = 20,
		.friendship = 70,
		.growthRate = GROWTH_SLOW,
		.eggGroups = { EGG_GROUP_HUMAN_LIKE, EGG_GROUP_HUMAN_LIKE },
		.abilities = { ABILITY_AVERNIC, ABILITY_MERCILESS, ABILITY_0 },
		.height = 0,
		.weight = 0,
	},
